#!/usr/bin/php
<?php

/* Set the namespace */
namespace adapt\scheduler;


/*
 * Prevent this task from being terminated early
 */
ignore_user_abort(true);

/*
 * Get the command line argument
 */
if (count($argv) == 2){
    
    /* Boot the framework */
    list($path, $rest) = explode("/extensions", $argv[0]);
    
    define('TEMP_PATH', sys_get_temp_dir() . '/');
    define('ADAPT_PATH', $path . "/");
    define('FRAMEWORK_PATH', ADAPT_PATH . 'frameworks/');
    define('EXTENSION_PATH', ADAPT_PATH . 'extensions/');
    define('TEMPLATE_PATH', ADAPT_PATH . 'templates/');
    define('APPLICATION_PATH', ADAPT_PATH . 'applications/');
    define('ADAPT_STARTED', true);
    require(FRAMEWORK_PATH . 'adapt/boot.php');
    
    
    $task_log = new model_task_log($argv[1]);
    if ($task_log->is_loaded){
        $task = new model_task($task_log->task_id);
        if ($task->is_loaded){
            $task_class = $task->class_name;
            if (class_exists($task_class)){
                $t = new $task_class($task_log, $task);
                if ($t && $t instanceof task){
                    $t->spawn();
                }
            }
        }
    }
    //$task = new task($arvg[1]);
    //$task->spawn();
}

?>